name: CI

on:
  push:
    branches-ignore: [deploy]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust-version: ['1.56.0', '1.57.0']

    steps:
    - name: Checkout pkgcraft
      uses: actions/checkout@v2
      with:
        repository: pkgcraft/pkgcraft
        path: pkgcraft

    - name: Checkout pkgcraft-c
      uses: actions/checkout@v2
      with:
        repository: pkgcraft/pkgcraft-c
        path: pkgcraft-c

    - name: Move repos into expected locations
      run: mv pkgcraft pkgcraft-c ../

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update deps
      run: |
        cargo update --manifest-path=../pkgcraft-c/Cargo.toml
        # hashFiles() for cache key creation doesn't seem to work with relative paths
        cp ../pkgcraft-c/Cargo.lock ./

    - name: Set up rust cache
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          ~/.rustup
          target
        key: v3-${{ matrix.os }}-rust-${{ matrix.rust-version }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: v3-${{ matrix.os }}-rust-${{ matrix.rust-version }}-cargo-

    - name: Set up rust toolchain ${{ matrix.rust-version }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-version }}
        profile: minimal
        override: true
        components: rustfmt

    - name: Install cargo-c
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo install cargo-c

    - name: Build C library
      run: cargo cinstall --prefix=${PWD}/pkgcraft --pkgconfigdir=${PWD}/pkgcraft --manifest-path=../pkgcraft-c/Cargo.toml --target-dir target

    - name: Install meson
      run: pip install meson

    - name: Install ninja and bash plugin support
      run: sudo apt install -y ninja-build bash-builtins

    - name: Build bash plugins
      run: |
        export PKG_CONFIG_PATH=pkgcraft
        meson setup build
        meson compile -C build -v
