name: CI

on:
  push:
    branches-ignore: [deploy]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install meson
      run: pip install meson

    - name: Install ninja and bash plugin support
      run: sudo apt install -y ninja-build bash-builtins

    - name: Build bash plugins
      run: |
        export PKG_CONFIG_PATH=pkgcraft
        meson setup build
        meson compile -C build -v
